### ISSUE TITLE
Dataset has multiple DSDs

### ISSUE THREAD

**Issue by lkitching** [traffordDataLab/opengovintelligence#1]
Running the following query:

```sparql 
SELECT * WHERE {
  <http://gmdatastore.org.uk/data/population/population-forecast-by-age-gender/2015> qb:structure ?struct .
}
```

returns two DSDs for the "Population forecasts 2015" dataset.

**Comment by rcatlord** [comment]
Hi Lee - the "Population forecasts 2015" dataset is one that SWIRRL added for us. Could you please test out the following that we transformed using table2qb:  

- Claimant count
- Households with lone parent not in employment
- Social rented households
- Working age adults with no qualifications

**Comment by lkitching** [comment]
@rcatlord - All the other datasets correctly specify a single DSD. The extra DSD for the population forcasts dataset is `http://gmdatastore.org.uk/data/structure/population/population-forecast-by-age-gender/2015` which does not have any other statements associated with it, so it looks like we can just delete the `<http://gmdatastore.org.uk/data/population/population-forecast-by-age-gender/2015> qb:structure <http://gmdatastore.org.uk/data/structure/population/population-forecast-by-age-gender/2015>` triple.
