### ISSUE TITLE
Some datasets do not have qb:measureType dimension

### ISSUE THREAD

**Issue by lkitching** [traffordDataLab/opengovintelligence#4]
Cubiql requires datasets to contain a `qb:measureType` dimension to indicate which measure type is used for each observation (multi-measure observations are not currently supported). The following query returns the datasets which do not specify a `qb:measureType` dimension:

```sparql
# Datasets must have a qb:measureType component

PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?this WHERE {
  ?this a qb:DataSet .
  FILTER NOT EXISTS {
    ?this qb:structure ?dsd .
    ?dsd qb:component ?comp .
    ?comp qb:dimension qb:measureType .
  }
}
```

This returns 4 datasets:
* `http://gmdatastore.org.uk/data/population-2011-census`
* `http://gmdatastore.org.uk/data/life-expectancy`
* `http://gmdatastore.org.uk/data/alcohol-related-hospital-stays`
* `http://gmdatastore.org.uk/data/business-register-employment-survey`

**Comment by BillSwirrl** [comment]
Add a measureType dimension to `http://gmdatastore.org.uk/data/business-register-employment-survey`

Add a triple to each observation:

```
?obs qb:measureType <http://gmdatastore.org.uk/def/measure-properties/count>
```

and add an appropriate component and codelist to the DSD

**Comment by BillSwirrl** [comment]
Fixed. This issue can now be closed

**Comment by itsozz** [comment]
Thanks Bill.
