### ISSUE TITLE
Reference areas do not have labels

### ISSUE THREAD

**Issue by lkitching** [traffordDataLab/opengovintelligence#5]
Cubiql expects each reference area has a corresponding label. The following query returns the areas without a label:

```sparql
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?this WHERE {
  { SELECT DISTINCT ?this WHERE {
      ?obs a qb:Observation .
      ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?this .
    }
  }

  FILTER NOT EXISTS {
    ?this <http://www.w3.org/2000/01/rdf-schema#label> ?label .
  }
}
```

**Comment by itsozz** [comment]
The areas returned without labels appear to be outside of Greater Manchester. We don't need these to be present in the dataset for the pilot.

**Comment by BillSwirrl** [comment]
datasets affected:

http://gmdatastore.org.uk/data/indices-of-deprivation-2015
http://gmdatastore.org.uk/data/alcohol-related-hospital-stays
http://gmdatastore.org.uk/data/life-expectancy

**Comment by BillSwirrl** [comment]
Have deleted life-expectancy and alcohol-related-hospital-stays as not needed.

For the deprivation dataset, need to delete the areas not in Greater Manchester.

**Comment by BillSwirrl** [comment]
fixed.  Can now close this issue

**Comment by itsozz** [comment]
Thanks Bill.
